import groovy.transform.Field

// HEADER CONFIGURATORS
@Field final String INPUTS_NAME = "InputsConfigurator"
@Field final String INPUTS_LABEL = "Inputs"
@Field final String INPUTS_URL = "QuoteInputHeaderConfigurator"
@Field final String COMPETITIVE_INFO_NAME = "CompetitiveConfigurator"
@Field final String COMPETITIVE_INFO_LABEL = "Competitive Info"
@Field final String COMPETITIVE_INFO_URL = "QuoteCompetitiveHeaderConfigurator"
@Field final String EXISTING_INPUTS_URL = "QuoteExistingInputHeaderConfigurator"
@Field final String PRICE_PROTECTION_CONFIGURATOR_NAME = "PriceProtectionConfigurator"
@Field final String PRICE_PROTECTION_CONFIGURATOR_LABEL = "Price Protection"
@Field final String PRICE_PROTECTION_CONFIGURATOR_URL = "QuotePriceProtectionHeaderConfigurator"
@Field final String CONTRACT_PO_MATRIX_CONFIGURATOR_URL = "QuoteContractPOMatrixConfigurator"

// HEADER INPUTS
@Field final String SOLD_TO_ID = "SoldToInput"
@Field final String SOLD_TO_LABEL = "Sold to"
@Field final String SOLD_TO_URL = "InputSoldToFilter"
@Field final String SHIP_TO_ID = "ShipToInput"
@Field final String SHIP_TO_LABEL = "Ship to(s)"
@Field final String SALES_ORG_ID = "SalesOrgInput"
@Field final String SALES_ORG_LABEL = "Sales Org"
@Field final String EXTERNAL_NOTES_ID = "ExternalNotesInput"
@Field final String EXTERNAL_NOTES_LABEL = "External Notes"
@Field final String CONTRACT_PO_ID = "ContractPOInput"
@Field final String CONTRACT_PO_LABEL = "Contract PO Matrix"
@Field final String SOLD_TO_HIDDEN_ID = "SoldToHiddenInput"
@Field final String CONTRACT_NUMBER_ID = "ContractNumberInput"
@Field final String CONTRACT_NUMBER_LABEL = "Contract Number(s)"
@Field final String DIVISION_ID = "DivisionInput"
@Field final String DIVISION_LABEL = "Division"
@Field final String EXPIRY_DATE_DEFAULTED = "ExpiryDateDefaultedInput"
@Field final String PROSPECTIVE_BUSINESS_ID = "ProspectiveBusinessInput"
@Field final String PROSPECTIVE_BUSINESS_LABEL = "Prospective Business"
@Field final String CONTRACT_EFFECTIVE_DATE_ID = "ContractEffectiveDateInput"
@Field final String CONTRACT_EFFECTIVE_DATE_LABEL = "Contract Effective Date"
@Field final String SOLD_TO_ONLY_QUOTE_ID = "SoldToOnlyQuoteInput"
@Field final String SOLD_TO_ONLY_QUOTE_LABEL = "Sold To Only Quote"
@Field final String INCLUDE_ADDER_ID = "IncludeAdderInput"
@Field final String INCLUDE_ADDER_LABEL = "Include Adder"
@Field final String PRIMARY_CONTACT_ID = "PrimaryContactInput"
@Field final String PRIMARY_CONTACT_LABEL = "Primary Contact"
@Field final String SELECTED_CONTRACTS_HIDDEN = "SelectedContractsHiddenInput"
@Field final String SELECTED_SOLD_TO_HIDDEN = "SelectedSoldTosHiddenInput"
@Field final String SELECTED_SHIP_TO_HIDDEN = "SelectedShipTosHiddenInput"
@Field final String IMPORT_LINE_ITEMS_ID = "ImportLineItemsInput"
@Field final String IMPORT_LINE_ITEMS_LABEL = "Import Line Items"
@Field final String HEADER_HAS_CHANGED_ID = "HeaderHasChangedInput"
@Field final String SOLD_TO_VALUES_HIDDEN_ID = "SoldToValuesHiddenInput"
@Field final String MATERIAL_ID = "MaterialInput"
@Field final String MATERIAL_LABEL = "Material"
@Field final String MATERIAL_URL = "InputMaterialFilter"
@Field final String MATERIAL_VALUES_HIDDEN_ID = "MaterialValuesHiddenInput"
@Field final String LINE_REJECTED_ID = "LineRejectedInput"
@Field final String LINE_REJECTED_LABEL = "Line Rejected"
@Field final String SALES_PERSON_ID = "SalesPersonInput"
@Field final String SALES_PERSON_LABEL = "Sales Person"
@Field final String ADD_CONTRACT_LINES_ID = "AddContractLinesInput"
@Field final String ADD_CONTRACT_LINES_LABEL = "Add Contract Lines"

// HEADER COMPETITIVE INPUTS
@Field final String PRIMARY_COMPETITOR_ID = "PrimaryCompetitorInput"
@Field final String PRIMARY_COMPETITOR_LABEL = "Primary Competitor"
@Field final String COMPETITIVE_SITUATION_ID = "CompetitiveSituationInput"
@Field final String COMPETITIVE_SITUATION_LABEL = "Competitive Situation"

// HEADER PRICE PROTECTION INPUTS
@Field final String PRICE_PROTECTION_ID = "PriceProtectionInput"
@Field final String PRICE_PROTECTION_LABEL = "Price Protection"
@Field final String NUMBER_OF_DAYS_ID = "NumberOfDaysInput"
@Field final String NUMBER_OF_DAYS_LABEL = "Number of Days"
@Field final String MOVEMENT_TIMING_ID = "MovementTimingInput"
@Field final String MOVEMENT_TIMING_LABEL = "Movement Timing"
@Field final String MOVEMENT_START_ID = "MovementStartInput"
@Field final String MOVEMENT_START_LABEL = "Movement Start Month"
@Field final String MOVEMENT_DAY_ID = "MovementDayInput"
@Field final String MOVEMENT_DAY_LABEL = "Movement Day"