import groovy.transform.Field

// COMPANY PARAMETER TABLES
@Field final String SALES_ORG = "SalesOrg"
@Field final String DROPDOWN_OPTIONS = "DropdownOptions"
@Field final String PLANT = "Plant"
@Field final String PRICING_FORMULA = "PricingFormula"
@Field final String MEANS_OF_TRANSPORTATION = "MeansofTransportation"
@Field final String MODE_OF_TRANSPORTATION = "ModeofTransportation"
@Field final String UOM_DESCRIPTION = "UOMDescription"
@Field final String PRICELIST = "Pricelist"
@Field final String QUOTE_STATUS = "ApprovedQuoteStatus"
@Field final String QUOTE_STATUS_FOR_SCALES = "ApprovedQuoteStatusForScales"
@Field final String LINE_IDS_FOR_CR_STATUS = "LineIDsForCRStatus"
@Field final String QUOTES_FOR_CR_STATUS = "QuotesForCRStatus"
@Field final String CONTRACT_UUID = "ContractUUID"
@Field final String SHIPPING_POINT = "ShippingPoint"
@Field final String PLANT_SHIPPING_POINT = "PlantShippingPoint"
@Field final String GLOBAL_UOM_CONVERSION = "GlobalUOMConversion"
@Field final String UOM_CONVERSION = "UOMConversion"
@Field final String DIVISION = "Division"
@Field final String MODE_OF_TRANSPORTATION_GROUP = "ModeOfTransportationGroup"
@Field final String GUARDRAIL = "Guardrail"
@Field final String APPROVERS_TABLE = "ApproversTable"
@Field final String INCO_TERM = "IncoTerm"
@Field final String INDEX_VALUES = "IndexValues"
@Field final String EXCLUSIONS = "Exclusions"
@Field final String GUARDRAILS = "Guardrails"
@Field final String PLANT_DIFFERENTIAL = "PlantDifferential"
@Field final String PACKAGE_DIFFERENTIALS = "PackageDifferentials"
@Field final String WORKFLOW_EMAILS = "WorkflowEmails"
@Field final String C4C_UOM = "C4CUOM"
@Field final String CONFIGURATIONS_BREAKDOWN_REFERENCE = "ConfigurationsBreakdownReference"
@Field final String PRICELIST_FOOTERS = "PricelistFooters"
@Field final String DASHBOARD_FOOTERS = "DashboardFooters"
@Field final String PENDING_CONDITION_RECORDS = "PendingConditionRecords"

// EXTENSIONS
@Field final String PRODUCT_EXTENSION_COST = "Cost"
@Field final String PRODUCT_EXTENSION_PRODUCT_HIERARCHY = "ProductHierarchy"
@Field final String CUSTOMER_EXTENSION_PARTNER_FUNCTION = "PartnerKNVP"

// DATA SOURCES
@Field final String DATA_SOURCE_CONTRACT = "Contract"
@Field final String DATA_SOURCE_QUOTES = "Quotes"
@Field final String DATA_SOURCE_QUOTES_SCALES = "QuoteScales"
@Field final String DATA_SOURCE_PRICING = "ZBPL"
@Field final String DATA_SOURCE_LIST_PRICE = "ListPrice"
@Field final String DATA_SOURCE_ZDGS = "ZDGS"
@Field final String DATA_SOURCE_ZDGS_SCALES = "ZDGSScales"
@Field final String DATA_SOURCE_ZBPL_SCALES = "ZBPLScales"