import net.pricefx.common.util.CalendarUtil
import net.pricefx.domain.CustomerGroup
import net.pricefx.domain.ProductGroup
import net.pricefx.formulaengine.DatamartContext

/**
 * Retrieves raw query data for the Revenue Breakdown data dashboard based on the provided input filters.
 * The mappings for the DM fields are retrieved using the SQL_CONFIGURATION.
 * If both aggregation dimensions are selected as None no data is returned.
 * The data retrieved is in the following structure:
 * [
 *   "oldRevenue" : 63579817,
 *   "volumeEffect" : -32334535,
 *   "priceEffect" : 8790089,
 *   "mixEffect" : 2575,
 *   "lostBusiness" : -25856628,
 *   "newBusiness" : 2342,
 *   "newRevenue" : 14183660
 * ]
 * @param productElement product filter as generated by the product group entry user input.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerElement customer filter as generated by the customer group entry user input.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param periodElement element defining the first period, can be a year or a combination of year with a quarter
 * @param comparisonPeriodElement element defining the second period, can be a year or a combination of year with a quarter
 * @param targetCurrencyCode currency code that the dashboards is going to be displayed in. Used for currency conversion.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param genericFilter generic filter as generated by the generic filter user input.
 * @return raw query data for the Revenue Breakdown
 */
Map getRevenueBreakdownData(def productElement,
                            String productAggregation,
                            def customerElement,
                            String customerAggregation,
                            def periodElement,
                            def comparisonPeriodElement,
                            String targetCurrencyCode,
                            Map sqlConfiguration,
                            Filter genericFilter) {
    if (isDimensionNone(customerAggregation) && isDimensionNone(productAggregation)) {
        return [:]
    }

    def datamartContext = api.getDatamartContext()

    DatamartContext.Query baseQueryDefinition = getRevenueBaseQuery(datamartContext,
            sqlConfiguration,
            productElement,
            productAggregation,
            customerElement,
            customerAggregation,
            genericFilter)

    DatamartContext.Query comparisonPeriodQuery = getPeriodQuery(datamartContext,
            baseQueryDefinition,
            comparisonPeriodElement,
            sqlConfiguration,
            targetCurrencyCode)

    DatamartContext.Query periodQuery = getPeriodQuery(datamartContext,
            baseQueryDefinition,
            periodElement,
            sqlConfiguration,
            targetCurrencyCode)

    String sqlQuery = getRevenueBreakdownSQLStatement(productAggregation, customerAggregation, sqlConfiguration)

    return datamartContext.executeSqlQuery(sqlQuery, comparisonPeriodQuery, periodQuery)?.getAt(0)
}

/**
 * Retrieves the base query for the Revenue Breakdown, the base query is used for both period queries in the dashboard.
 * Contains all common elements for both period queries, only thing that is missing is the period specific date range.
 * @param dmCtx data mart context object.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param productElement product filter as generated by the product group entry user input.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerElement customer filter as generated by the customer group entry user input.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param genericFilter generic filter as generated by the generic filter user input.
 * @return a DatamartContext.Query object describing the base query used in Revenue Breakdown dashboard
 */
protected DatamartContext.Query getRevenueBaseQuery(DatamartContext dmCtx,
                                                    Map sqlConfiguration,
                                                    def productElement,
                                                    String productAggregation,
                                                    def customerElement,
                                                    String customerAggregation,
                                                    Filter genericFilter) {
    def inputConfig = libs.SIP_Dashboards_Commons.ConstConfig.CAUSALITY_DASHBOARD_CONFIG.INPUTS
    def datamart = dmCtx.getDatamart(sqlConfiguration.datamartName)
    def baseQueryDefinition = dmCtx.newQuery(datamart, true)

    addAggregationLevel(baseQueryDefinition,
            productAggregation,
            sqlConfiguration.productId,
            inputConfig.PRODUCT_AGGREGATION.ENTRY_CATEGORY_FIELD)
    addAggregationLevel(baseQueryDefinition,
            customerAggregation,
            sqlConfiguration.customerId,
            inputConfig.CUSTOMER_AGGREGATION.ENTRY_CATEGORY_FIELD)

    baseQueryDefinition.select("SUM(${sqlConfiguration.invoicePrice})", "IP")
    baseQueryDefinition.select("SUM(${sqlConfiguration.quantity})", "V") //
    baseQueryDefinition.select("SUM(${sqlConfiguration.invoicePrice}) / SUM(${sqlConfiguration.quantity})", "IPpu")

    baseQueryDefinition.where(productElement as ProductGroup)
    baseQueryDefinition.where(customerElement as CustomerGroup)
    baseQueryDefinition.where(Filter.isNotNull(sqlConfiguration.invoicePrice),
            Filter.isNotNull(sqlConfiguration.quantity))

    baseQueryDefinition.having(Filter.greaterThan("IP", 0),
            Filter.greaterThan("V", 0))

    if (genericFilter) {
        baseQueryDefinition.where(genericFilter)
    }

    return baseQueryDefinition
}

/**
 * Retrieves raw query data for the Revenue Breakdown data dashboard based on the provided input filters.
 * The mappings for the DM fields are retrieved using the SQL_CONFIGURATION.
 * If both aggregation dimensions are selected as None no data is returned.
 * The data retrieved is in the following structure:
 * [
 *   "period1Margin" : 27313065,
 *   "volumeEffect" : -13942114,
 *   "priceEffect" : 59216582,
 *   "costEffect" : 186819,
 *   "mixEffect" : -16545,
 *   "lostBusiness" : -11050387,
 *   "newBusiness" : 331667,
 *   "period2Margin" : 11470263
 * ]
 * @param productElement product filter as generated by the product group entry user input.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerElement customer filter as generated by the customer group entry user input.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param periodElement element defining the first period, can be a year or a combination of year with a quarter
 * @param comparisonPeriodElement element defining the second period, can be a year or a combination of year with a quarter
 * @param targetCurrencyCode currency code that the dashboards is going to be displayed in. Used for currency conversion.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param model calculation model selected by the user in the Model user input. Available models defined in libs.SIP_Dashboards_Commons.ConstConfig.MARGIN_BREAKDOWN_DASHBOARD_CONFIG
 * @param genericFilter generic filter as generated by the generic filter user input.
 * @return raw query data for the Margin Breakdown
 */
Map getMarginBreakdownData(def productElement,
                           String productAggregation,
                           def customerElement,
                           String customerAggregation,
                           def periodElement,
                           def comparisonPeriodElement,
                           String targetCurrencyCode,
                           Map sqlConfiguration,
                           String model,
                           Filter genericFilter) {
    if (isDimensionNone(customerAggregation) && isDimensionNone(productAggregation)) {
        return [:]
    }

    def datamartContext = api.getDatamartContext()
    DatamartContext.Query baseQueryDef = getMarginBaseQuery(datamartContext,
            sqlConfiguration,
            productElement,
            productAggregation,
            customerElement,
            customerAggregation,
            genericFilter)

    DatamartContext.Query comparisonPeriodQuery = getPeriodQuery(datamartContext,
            baseQueryDef,
            comparisonPeriodElement,
            sqlConfiguration,
            targetCurrencyCode)

    DatamartContext.Query periodQuery = getPeriodQuery(datamartContext,
            baseQueryDef,
            periodElement,
            sqlConfiguration,
            targetCurrencyCode)

    String sqlStatement = getMarginBreakdownModelSQLStatement(model, productAggregation, customerAggregation, sqlConfiguration)

    return datamartContext.executeSqlQuery(sqlStatement, comparisonPeriodQuery, periodQuery)?.getAt(0)
}

/**
 * Retrieves the SQL statement used based on the provided calculation model.
 * @param model calculation model selected by the user in the Model user input. Available models defined in libs.SIP_Dashboards_Commons.ConstConfig.MARGIN_BREAKDOWN_DASHBOARD_CONFIG
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @return raw SQL statement used to calculate values based on selected calculation model
 */
protected String getMarginBreakdownModelSQLStatement(String model, String productAggregation, String customerAggregation, Map sqlConfiguration) {
    return (sqlConfiguration.breakdownMode == libs.SIP_Dashboards_Commons.ConstConfig.BREAKDOWN_CALCULATION_DEFINITION.LEGACY) ?
            getLegacyMarginBreakdownSQLStatement(model, productAggregation, customerAggregation) :
            getStandardMarginBreakdownSQLStatement(productAggregation, customerAggregation)
}

/**
 * Retrieves the base query for the Margin Breakdown, the base query is used for both period queries in the dashboard.
 * Contains all common elements for both period queries, only thing that is missing is the period specific date range.
 * @param dmCtx data mart context object.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param productElement product filter as generated by the product group entry user input.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerElement customer filter as generated by the customer group entry user input.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param genericFilter generic filter as generated by the generic filter user input.
 * @return a DatamartContext.Query object describing the base query used in Margin Breakdown dashboard
 */
protected DatamartContext.Query getMarginBaseQuery(DatamartContext dmCtx,
                                                   Map sqlConfiguration,
                                                   def productElement,
                                                   String productAggregation,
                                                   def customerElement,
                                                   String customerAggregation,
                                                   Filter genericFilter) {
    def datamart = dmCtx.getDatamart(sqlConfiguration.datamartName)
    def baseQueryDefinition = dmCtx.newQuery(datamart, true)

    addAggregationLevel(baseQueryDefinition, productAggregation, sqlConfiguration.productId, "productId")
    addAggregationLevel(baseQueryDefinition, customerAggregation, sqlConfiguration.customerId, "customerId")
    baseQueryDefinition.select("SUM(${sqlConfiguration.grossMargin})", "margin")
    baseQueryDefinition.select("SUM(${sqlConfiguration.quantity})", "'volume'")
    baseQueryDefinition.select("SUM(${sqlConfiguration.invoicePrice}) / SUM(${sqlConfiguration.quantity})", "invoicePricePerUnit")
    baseQueryDefinition.select("SUM(${sqlConfiguration.grossMargin}) / SUM(${sqlConfiguration.quantity})", "marginPerUnit")
    baseQueryDefinition.select("SUM(${sqlConfiguration.costs}) / SUM(${sqlConfiguration.quantity})", "costPerUnit")

    baseQueryDefinition.where(productElement as ProductGroup)
    baseQueryDefinition.where(customerElement as CustomerGroup)
    baseQueryDefinition.where(Filter.isNotNull(sqlConfiguration.grossMargin),
            Filter.isNotNull(sqlConfiguration.invoicePrice),
            Filter.isNotNull(sqlConfiguration.quantity))

    baseQueryDefinition.having(Filter.greaterThan("'volume'", 0))

    if (genericFilter) {
        baseQueryDefinition.where(genericFilter)
    }

    return baseQueryDefinition
}

/**
 * Creates a query object for a given period used in Causality Dashboards.
 * Requires a base query object to extend.
 * Adds only date based data.
 * @param dmCtx data mart context object.
 * @param baseQueryDefinition definition of the query as defined by the Dashboard Library. Generated by getMarginBaseQuery or getRevenueBaseQuery
 * @param dateElement either Period or ComparisonPeriod elements, used to create date filters
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param targetCurrencyCode currency code that the dashboards is going to be displayed in. Used for currency conversion.
 * @return query object to be used as main data fetch tool for all Causality Dashboards.
 */
protected DatamartContext.Query getPeriodQuery(DatamartContext dmCtx,
                                               DatamartContext.Query baseQueryDef,
                                               def dateElement,
                                               Map sqlConfiguration,
                                               String targetCurrencyCode) {
    def query = dmCtx.newQuery(baseQueryDef)
    def periodStartDate = dateElement.getStartDate()
    def periodEndDate = dateElement.getEndDate()
    query.where(Filter.lessOrEqual(sqlConfiguration.pricingDate, periodEndDate),
            Filter.greaterOrEqual(sqlConfiguration.pricingDate, periodStartDate))
    query.setOptions([currency: targetCurrencyCode])

    return query
}

/**
 * Appends the base query definition with aggregation field if required.
 * Selection of None dimension prevents the addition.
 * @param baseQueryDefinition definition of the query as defined by the Dashboard Library. Generated by getMarginBaseQuery or getRevenueBaseQuery
 * @param aggregation product/customer aggregation as selected by the product/customer aggregation entry user input.
 * @param sqlField field that acts as a fallback in case the aggregation is not provided.
 * @param sqlAlias alias for the aggregation field that will be returned from the query
 */
protected void addAggregationLevel(def baseQueryDefinition, String aggregation, String sqlField, String sqlAlias) {
    if (!aggregation || aggregation == libs.SIP_Dashboards_Commons.ConstConfig.EMPTY_DIMENSION_KEY) {
        return
    }

    String aggregationField = getAggregationLevelSQLField(aggregation, sqlField)
    baseQueryDefinition.select(aggregationField, sqlAlias)
}

/**
 * Retrieves which of the provided entries should be used.
 * If the aggregation input is not provided or it's equal to sqlField the sqlField is returned,
 * otherwise the aggregation is used.
 * @param aggregation product/customer aggregation as selected by the product/customer aggregation entry user input.
 * @param sqlField field that acts as a fallback in case the aggregation is not provided.
 * @return either aggregation or sqlField depending on the data availability
 */
protected String getAggregationLevelSQLField(String aggregation, String sqlField) {
    return !aggregation || (aggregation == sqlField) ? sqlField : aggregation

}

/**
 * Retrieves the main SQL statement for the Revenue Breakdown Dashboard
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @return raw SQL statement returning all data required for Revenue Dashboard
 */
protected String getRevenueBreakdownSQLStatement(String productAggregation, String customerAggregation, Map sqlConfiguration) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return (sqlConfiguration.breakdownMode == libs.SIP_Dashboards_Commons.ConstConfig.BREAKDOWN_CALCULATION_DEFINITION.LEGACY) ?
            getLegacyRevenueBreakdownSQLStatement(joinFields, lostBusinessWhere, newBusinessWhere) :
            getStandardRevenueBreakdownSQLStatement(joinFields, lostBusinessWhere, newBusinessWhere)
}

/**
 * Retrieves the legacy SQL statement for the Revenue Breakdown Dashboard
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param joinFields fields used to join T1 and T2.
 * @param lostBusinessWhere sql WHERE clause to retrieve lost business.
 * @param newBusinessWhere sql WHERE clause to retrieve new business.
 * @return raw SQL statement returning all data required for Revenue Dashboard
 */
protected String getLegacyRevenueBreakdownSQLStatement(String joinFields, String lostBusinessWhere, String newBusinessWhere) {
    return """SELECT
                ROUND(PERIOD1.IP) AS 'oldRevenue',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.IP) AS 'lostBusiness',
                ROUND(PERIOD2.IP - PERIOD1.IP - (COALESCE(-LOST_DATA.IP, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.IP, 0))) AS 'otherEffects',
                ROUND(NEW_DATA.IP) AS 'newBusiness',
                ROUND(PERIOD2.IP) AS 'newRevenue'
                FROM (SELECT
                      SUM((T2.IPpu - T1.IPpu) * T2.V) AS PriceEffect,
                      (SUM(T2.V)-SUM(T1.V)) * (SUM(T1.IP) / SUM(T1.V)) AS VolumeEffect,
                      SUM(T1.IPpu * (T2.V/TOTAL.T2V - T1.V/TOTAL.T1V)) * SUM(T2.V) AS MixEffect
                      FROM T2
                          INNER JOIN T1 ON ${joinFields},
                        (SELECT SUM(T1.V) AS T1V, SUM(T2.V) AS T2V
                          FROM T2 INNER JOIN T1 ON
                            ${joinFields}) TOTAL) COMMON_DATA,
                    (SELECT SUM(T1.IP) AS ip FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                    (SELECT SUM(T2.IP) AS ip FROM T1
                        RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                    (SELECT SUM(T1.IP) IP FROM T1) PERIOD1,
                    (SELECT SUM(T2.IP) IP FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the standard SQL statement for the Revenue Breakdown Dashboard
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param joinFields fields used to join T1 and T2.
 * @param lostBusinessWhere sql WHERE clause to retrieve lost business.
 * @param newBusinessWhere sql WHERE clause to retrieve new business.
 * @return raw SQL statement returning all data required for Revenue Dashboard
 */
protected String getStandardRevenueBreakdownSQLStatement(String joinFields, String lostBusinessWhere, String newBusinessWhere) {
    return """SELECT
                ROUND(PERIOD1.IP) AS 'oldRevenue',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(PERIOD2.IP - PERIOD1.IP - (COALESCE(-LOST_DATA.IP, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.IP, 0))) AS 'otherEffects',
                ROUND(-LOST_DATA.IP) AS 'lostBusiness',
                ROUND(NEW_DATA.IP) AS 'newBusiness',
                ROUND(PERIOD2.IP) AS 'newRevenue'
                FROM (SELECT
                        SUM((T2.V + T1.V) / 2) * SUM((T2.V / TOTAL.T2V + T1.V / TOTAL.T1V) / 2 * (T2.IPpu - T1.IPpu)) AS PriceEffect,
                        SUM(T2.V - T1.V) * SUM((T2.V / TOTAL.T2V * T2.IPpu + T1.V / TOTAL.T1V * T1.IPpu) / 2) AS VolumeEffect,
                        SUM((T2.V + T1.V) / 2) * SUM((T2.V / TOTAL.T2V - T1.V / TOTAL.T1V) * (T2.IPpu + T1.IPpu) / 2) AS MixEffect
                      FROM T2
                          INNER JOIN T1 ON ${joinFields},
                        (SELECT SUM(T1.V) AS T1V, SUM(T2.V) AS T2V
                          FROM T2 INNER JOIN T1 ON
                            ${joinFields}) TOTAL) COMMON_DATA,
                    (SELECT SUM(T1.IP) AS ip FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                    (SELECT SUM(T2.IP) AS ip FROM T1
                        RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                    (SELECT SUM(T1.IP) IP FROM T1) PERIOD1,
                    (SELECT SUM(T2.IP) IP FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the Net calculation model.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getNetMarginBreakdownSQLStatement(String productAggregation, String customerAggregation) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return """SELECT
                ROUND(PERIOD1.Margin) AS 'period1Margin',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(-COMMON_DATA.CostEffect) AS 'costEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.Margin) AS 'lostBusiness',
                ROUND(NEW_DATA.Margin) AS 'newBusiness',
                ROUND(PERIOD2.Margin) AS 'period2Margin',
                ROUND(PERIOD2.Margin - PERIOD1.Margin - (COALESCE(-LOST_DATA.Margin, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(-COMMON_DATA.CostEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.Margin, 0))) AS 'otherEffects'
                FROM (SELECT
                          SUM((T2.InvoicePricePerUnit - T1.InvoicePricePerUnit) * T1.Volume) AS PriceEffect,
                          SUM((T2.Volume - T1.Volume) * T1.MarginPerUnit) AS VolumeEffect,
                          SUM((T2.CostPerUnit - T1.CostPerUnit) * T1.Volume) AS CostEffect,
                          SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) * (T1.MarginPerUnit - (T1.Margin/TOTAL.T1Volume))) * SUM(T1.Volume) AS MixEffect
                          FROM T2
                             INNER JOIN T1 ON ${joinFields},
                             (SELECT SUM(T1.Volume) AS T1Volume, SUM(T2.Volume) AS T2Volume
                              FROM T2 INNER JOIN T1 ON
                               ${joinFields}) TOTAL) COMMON_DATA,
                      (SELECT SUM(T1.Margin) AS Margin FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                      (SELECT SUM(T2.Margin) AS Margin FROM T1
                       RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                      (SELECT SUM(T1.Margin) Margin FROM T1) PERIOD1,
                      (SELECT SUM(T2.Margin) Margin FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the legacy mode.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param model calculation model selected by the user in the Model user input. Available models defined in libs.SIP_Dashboards_Commons.ConstConfig.MARGIN_BREAKDOWN_DASHBOARD_CONFIG
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getLegacyMarginBreakdownSQLStatement(String model, String productAggregation, String customerAggregation) {
    def commonsConstConfig = libs.SIP_Dashboards_Commons.ConstConfig
    String sqlStatement

    switch (model) {
        case commonsConstConfig.MARGIN_BREAKDOWN_GROSS_CHART_KEY:
            sqlStatement = getGrossMarginBreakdownSQLStatement(productAggregation, customerAggregation)
            break
        case commonsConstConfig.MARGIN_BREAKDOWN_AVERAGES_CHART_KEY:
            sqlStatement = getAveragesMarginBreakdownSQLStatement(productAggregation, customerAggregation)
            break
        case commonsConstConfig.MARGIN_BREAKDOWN_MOST_USED_CHART_KEY:
            sqlStatement = getMostUsedMarginBreakdownSQLStatement(productAggregation, customerAggregation)
            break
        default:
            sqlStatement = getNetMarginBreakdownSQLStatement(productAggregation, customerAggregation)
            break
    }

    return sqlStatement
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the standard mode.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getStandardMarginBreakdownSQLStatement(String productAggregation, String customerAggregation) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return """SELECT
                ROUND(PERIOD1.Margin) AS 'period1Margin',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(-COMMON_DATA.CostEffect) AS 'costEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.Margin) AS 'lostBusiness',
                ROUND(NEW_DATA.Margin) AS 'newBusiness',
                ROUND(PERIOD2.Margin) AS 'period2Margin',
                ROUND(PERIOD2.Margin - PERIOD1.Margin - (COALESCE(-LOST_DATA.Margin, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(-COMMON_DATA.CostEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.Margin, 0))) AS 'otherEffects'
                FROM (SELECT
                          SUM((T2.Volume+T1.Volume)/2) * SUM((T2.Volume/TOTAL.T2Volume+T1.Volume/TOTAL.T1Volume)/2 * (T2.InvoicePricePerUnit - T1.InvoicePricePerUnit)) AS PriceEffect,
                          SUM(T2.Volume-T1.Volume) * SUM((T2.Volume/TOTAL.T2Volume*T2.MarginPerUnit + T1.Volume/TOTAL.T1Volume*T1.MarginPerUnit)/2) AS VolumeEffect,
                          (SUM((T2.Volume+T1.Volume)/2) * SUM((T2.Volume/TOTAL.T2Volume+T1.Volume/TOTAL.T1Volume)/2 * (T2.CostPerUnit - T1.CostPerUnit))) AS CostEffect,
                          SUM((T2.Volume+T1.Volume)/2) * SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) * (T2.MarginPerUnit+T1.MarginPerUnit)/2) AS MixEffect
                          FROM T2
                            INNER JOIN T1 ON ${joinFields},
                            (SELECT SUM(T1.Volume) AS T1Volume, SUM(T2.Volume) AS T2Volume
                              FROM T2 INNER JOIN T1 ON
                               ${joinFields}) TOTAL) COMMON_DATA,
                      (SELECT SUM(T1.Margin) AS Margin FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                      (SELECT SUM(T2.Margin) AS Margin FROM T1
                        RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                      (SELECT SUM(T1.Margin) Margin FROM T1) PERIOD1,
                      (SELECT SUM(T2.Margin) Margin FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the Gross calculation model.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getGrossMarginBreakdownSQLStatement(String productAggregation, String customerAggregation) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return """SELECT
                ROUND(PERIOD1.Margin) AS 'period1Margin',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(-COMMON_DATA.CostEffect) AS 'costEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.Margin) AS 'lostBusiness',
                ROUND(NEW_DATA.Margin) AS 'newBusiness',
                ROUND(PERIOD2.Margin) AS 'period2Margin',
                ROUND(PERIOD2.Margin - PERIOD1.Margin - (COALESCE(-LOST_DATA.Margin, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(-COMMON_DATA.CostEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.Margin, 0))) AS 'otherEffects'
                FROM (SELECT
                          SUM((T2.InvoicePricePerUnit - T1.InvoicePricePerUnit) * T2.Volume) AS PriceEffect,
                          SUM((T2.Volume - T1.Volume) * T2.MarginPerUnit) AS VolumeEffect,
                          SUM((T2.CostPerUnit - T1.CostPerUnit) * T2.Volume) AS CostEffect,
                          SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) * (T2.MarginPerUnit - (T2.Margin/TOTAL.T2Volume))) * SUM(T2.Volume) AS MixEffect
                          FROM T2
                            INNER JOIN T1 ON ${joinFields},
                            (SELECT SUM(T1.Volume) AS T1Volume, SUM(T2.Volume) AS T2Volume
                              FROM T2 INNER JOIN T1 ON
                               ${joinFields}) TOTAL) COMMON_DATA,
                      (SELECT SUM(T1.Margin) AS Margin FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                      (SELECT SUM(T2.Margin) AS Margin FROM T1
                        RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                      (SELECT SUM(T1.Margin) Margin FROM T1) PERIOD1,
                      (SELECT SUM(T2.Margin) Margin FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the Averages calculation model.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getAveragesMarginBreakdownSQLStatement(String productAggregation, String customerAggregation) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return """SELECT
                ROUND(PERIOD1.Margin) AS 'period1Margin',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(-COMMON_DATA.CostEffect) AS 'costEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.Margin) AS 'lostBusiness',
                ROUND(NEW_DATA.Margin) AS 'newBusiness',
                ROUND(PERIOD2.Margin) AS 'period2Margin',
                ROUND(PERIOD2.Margin - PERIOD1.Margin - (COALESCE(-LOST_DATA.Margin, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(-COMMON_DATA.CostEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.Margin, 0))) AS 'otherEffects'
                FROM (
                      SELECT
                          SUM((T2.InvoicePricePerUnit - T1.InvoicePricePerUnit) * ((T1.Volume+T2.Volume) / 2)) AS PriceEffect,
                          SUM((T2.Volume - T1.Volume) * ((T1.MarginPerUnit + T2.MarginPerUnit) / 2)) AS VolumeEffect,
                          SUM((T2.CostPerUnit - T1.CostPerUnit) * ((T1.Volume+T2.Volume)/2)) AS CostEffect,
                          SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) *
                                ((T2.MarginPerUnit - (T2.Margin/TOTAL.T2Volume)) + (T1.MarginPerUnit - (T1.Margin/TOTAL.T1Volume))) / 2) * (SUM(T1.Volume) + SUM(T2.Volume)) / 2 AS MixEffect
                          FROM T2
                             INNER JOIN T1 ON ${joinFields},
                             (SELECT SUM(T1.Volume) AS T1Volume, SUM(T2.Volume) AS T2Volume
                              FROM T2 INNER JOIN T1 ON
                               ${joinFields}) TOTAL) COMMON_DATA,
                      (SELECT SUM(T1.Margin) AS Margin FROM T1
                        LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                      (SELECT SUM(T2.Margin) AS Margin FROM T1
                        RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                      (SELECT SUM(T1.Margin) Margin FROM T1) PERIOD1,
                      (SELECT SUM(T2.Margin) Margin FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the main SQL statement for the Margin Breakdown Dashboard for the MostUsed calculation model.
 * The SQL returns all main data required by the dashboard.
 * The query requires two period queries named respectively T1 and T2.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement returning all data required for Margin Dashboard
 */
protected String getMostUsedMarginBreakdownSQLStatement(String productAggregation, String customerAggregation) {
    String joinFields = getQueryJoinFields(productAggregation, customerAggregation)
    String lostBusinessWhere = getNewLostBusinessQueryWhere("T2", productAggregation, customerAggregation)
    String newBusinessWhere = getNewLostBusinessQueryWhere("T1", productAggregation, customerAggregation)

    return """SELECT
                ROUND(PERIOD1.Margin) AS 'period1Margin',
                ROUND(COMMON_DATA.VolumeEffect) AS 'volumeEffect',
                ROUND(COMMON_DATA.PriceEffect) AS 'priceEffect',
                ROUND(-COMMON_DATA.CostEffect) AS 'costEffect',
                ROUND(COMMON_DATA.MixEffect) AS 'mixEffect',
                ROUND(-LOST_DATA.Margin) AS 'lostBusiness',
                ROUND(NEW_DATA.Margin) AS 'newBusiness',
                ROUND(PERIOD2.Margin) AS 'period2Margin',
                ROUND(PERIOD2.Margin - PERIOD1.Margin - (COALESCE(-LOST_DATA.Margin, 0) + COALESCE(COMMON_DATA.PriceEffect, 0) + COALESCE(COMMON_DATA.VolumeEffect, 0) + COALESCE(-COMMON_DATA.CostEffect, 0) + COALESCE(COMMON_DATA.MixEffect, 0) + COALESCE(NEW_DATA.Margin, 0))) AS 'otherEffects'
                FROM (
                      SELECT
                          SUM((T2.InvoicePricePerUnit - T1.InvoicePricePerUnit) * T2.Volume) AS PriceEffect,
                          SUM((T2.Volume - T1.Volume) * T1.MarginPerUnit) - SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) * (T1.MarginPerUnit - (T1.Margin/TOTAL.T1Volume))) * SUM(T2.Volume) AS VolumeEffect,
                          SUM((T2.CostPerUnit - T1.CostPerUnit) * T2.Volume) AS CostEffect,
                          SUM((T2.Volume/TOTAL.T2Volume - T1.Volume/TOTAL.T1Volume) * (T1.MarginPerUnit - (T1.Margin/TOTAL.T1Volume))) * SUM(T2.Volume) AS MixEffect
                          FROM T2
                              INNER JOIN T1 ON ${joinFields},
                              (SELECT SUM(T1.Volume) AS T1Volume, SUM(T2.Volume) AS T2Volume
                                  FROM T2 INNER JOIN T1 ON
                                   ${joinFields}) TOTAL) COMMON_DATA,
                      (SELECT SUM(T1.Margin) AS Margin FROM T1
                          LEFT OUTER JOIN T2 ON ${joinFields} ${lostBusinessWhere}) LOST_DATA,
                      (SELECT SUM(T2.Margin) AS Margin FROM T1
                          RIGHT OUTER JOIN T2 ON ${joinFields} ${newBusinessWhere}) NEW_DATA,
                      (SELECT SUM(T1.Margin) Margin FROM T1) PERIOD1,
                      (SELECT SUM(T2.Margin) Margin FROM T2) PERIOD2
                                 """
}

/**
 * Retrieves the join fields for all Causality dashboards based on the provided product/customer aggregations.
 * If both aggregations are present then tables are joined on both fields, if one is present then only one.
 * If no aggregation is provided an exception is thrown.
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return raw SQL statement defining the "join" part of the query
 */
protected String getQueryJoinFields(String productAggregation, String customerAggregation) {
    boolean isProductAggregationNone = isDimensionNone(productAggregation)
    boolean isCustomerAggregationNone = isDimensionNone(customerAggregation)

    if (!isProductAggregationNone && !isCustomerAggregationNone) {
        return "T1.ProductId = T2.ProductId AND T1.CustomerId = T2.CustomerId"
    } else if (!isProductAggregationNone) {
        return "T1.ProductId = T2.ProductId"
    } else if (!isCustomerAggregationNone) {
        return "T1.CustomerId = T2.CustomerId"
    }

    api.throwException("Missing aggregation")
    return null
}

/**
 * Retrieves the where statements that are based on the provided aggregations.
 * If both aggregations are present then tables require a where that will look up on both fields, if one is present then only one.
 * If no aggregation is provided an exception is thrown.
 * @param tableAlias which query should be affected by this statement, either T1 or T2
 * @param productAggregation product aggregation as selected by the product aggregation entry user input. Used in group by statements.
 * @param customerAggregation customer aggregation as selected by the customer aggregation entry user input. Used in group by statements.
 * @return where statement that will select either new or lost business based on the provided aggregations
 */
protected String getNewLostBusinessQueryWhere(String tableAlias, String productAggregation, String customerAggregation) {
    boolean isProductAggregationNone = isDimensionNone(productAggregation)
    boolean isCustomerAggregationNone = isDimensionNone(customerAggregation)

    if (!isProductAggregationNone && !isCustomerAggregationNone) {
        return "WHERE ${tableAlias}.ProductId IS NULL AND ${tableAlias}.CustomerId IS NULL"
    } else if (!isProductAggregationNone) {
        return "WHERE ${tableAlias}.ProductId IS NULL"
    } else if (!isCustomerAggregationNone) {
        return "WHERE ${tableAlias}.CustomerId IS NULL"
    }

    api.throwException("Missing aggregation")
    return null
}

/**
 * Checks if the provided aggregation is equal to None or null
 * @param aggregation product/customer aggregation as selected by the product/customer aggregation entry user input.
 * @return true if the dimension is None or null, false otherwise
 */
protected boolean isDimensionNone(String aggregation) {
    String noneDimension = libs.SIP_Dashboards_Commons.ConstConfig.EMPTY_DIMENSION_KEY

    return !aggregation || aggregation == noneDimension
}

String getTimePeriodLabel(Map periodConfigurator, CalendarUtil.TimePeriod period) {
    Script constConfig = libs.SIP_Dashboards_Commons.ConstConfig
    Script dateUtil = libs.SharedLib.DateUtils

    Map periodConfiguratorInputConfig = constConfig.CAUSALITY_PERIOD_CONFIGURATOR_CONFIG.INPUTS
    String periodType = periodConfigurator.getAt(periodConfiguratorInputConfig.PERIOD_TYPE.UNIQUE_KEY)
    String periodLabel
    String dateFormat = "dd/MM/yyyy"

    switch (periodType) {
        case constConfig.YTD_PERIOD_VALUE:
        case constConfig.CUSTOM_PERIOD_VALUE:
            periodLabel = "${dateUtil.getFormattedDate(period.getStartDate(), dateFormat)} - ${dateUtil.getFormattedDate(period.getEndDate(), dateFormat)}"
            break
        case constConfig.WEEK_PERIOD_VALUE:
        case constConfig.MONTH_PERIOD_VALUE:
        case constConfig.QUARTER_PERIOD_VALUE:
            periodLabel = api.getDatamartContext().calendar().getTimePeriodName(period)
            break
    }

    return periodLabel
}

CalendarUtil.TimePeriod getTimePeriodFromConfigurator(Map periodConfigurator) {
    Script constConfig = libs.SIP_Dashboards_Commons.ConstConfig
    Map periodConfiguratorInputConfig = constConfig.CAUSALITY_PERIOD_CONFIGURATOR_CONFIG.INPUTS
    String periodType = periodConfigurator.getAt(periodConfiguratorInputConfig.PERIOD_TYPE.UNIQUE_KEY)
    CalendarUtil.TimePeriod period

    if (periodType == constConfig.CUSTOM_PERIOD_VALUE) {
        period = getCustomTimePeriod(periodConfigurator, periodConfiguratorInputConfig, false)
    } else {
        String yearInputValue = periodConfigurator.getAt(periodConfiguratorInputConfig.YEAR.UNIQUE_KEY)

        if (periodType == constConfig.YTD_PERIOD_VALUE) {
            period = getYTDTimePeriod(yearInputValue)
        } else {
            String periodInputValue = periodConfigurator.getAt(periodConfiguratorInputConfig.PERIOD.UNIQUE_KEY)
            period = getTimePeriod(yearInputValue, periodInputValue)
        }
    }

    return period
}

CalendarUtil.TimePeriod getComparisonTimePeriodFromConfigurator(CalendarUtil.TimePeriod periodTimePeriod, Map periodConfigurator) {
    Script constConfig = libs.SIP_Dashboards_Commons.ConstConfig
    Map periodConfiguratorInputConfig = constConfig.CAUSALITY_PERIOD_CONFIGURATOR_CONFIG.INPUTS
    String periodType = periodConfigurator.getAt(periodConfiguratorInputConfig.PERIOD_TYPE.UNIQUE_KEY)
    CalendarUtil.TimePeriod period

    if (periodType == constConfig.CUSTOM_PERIOD_VALUE) {
        period = getCustomTimePeriod(periodConfigurator, periodConfiguratorInputConfig, true)
    } else {
        String yearInputValue = periodConfigurator.getAt(periodConfiguratorInputConfig.COMPARISON_YEAR.UNIQUE_KEY)

        if (periodType == constConfig.YTD_PERIOD_VALUE) {
            period = getYTDTimePeriod(yearInputValue)
        } else {
            String periodInputValue = periodConfigurator.getAt(periodConfiguratorInputConfig.COMPARISON_PERIOD.UNIQUE_KEY)
            period = getComparisonTimePeriod(yearInputValue, periodInputValue, periodTimePeriod)
        }
    }

    return period
}

protected CalendarUtil.TimePeriod getYTDTimePeriod(String yearInputValue) {
    int currentMonth = Calendar.getInstance().get(Calendar.MONTH) + 1
    int currentDay = Calendar.getInstance().get(Calendar.DAY_OF_MONTH)

    return libs.SIP_Dashboards_Commons.QueryUtils.createCustomTimePeriod("${yearInputValue}-01-01", "${yearInputValue}-${currentMonth}-${currentDay}")
}

protected CalendarUtil.TimePeriod getCustomTimePeriod(Map periodConfigurator, Map periodConfiguratorInputConfig, boolean isComparison) {
    String dateFrom
    String dateTo

    if (isComparison) {
        dateFrom = periodConfigurator.getAt(periodConfiguratorInputConfig.COMPARISON_DATE_FROM.UNIQUE_KEY)
        dateTo = periodConfigurator.getAt(periodConfiguratorInputConfig.COMPARISON_DATE_TO.UNIQUE_KEY)
    } else {
        dateFrom = periodConfigurator.getAt(periodConfiguratorInputConfig.DATE_FROM.UNIQUE_KEY)
        dateTo = periodConfigurator.getAt(periodConfiguratorInputConfig.DATE_TO.UNIQUE_KEY)
    }

    return libs.SIP_Dashboards_Commons.QueryUtils.createCustomTimePeriod(dateFrom, dateTo)
}

protected CalendarUtil.TimePeriod getTimePeriod(String yearEntry, String periodEntry = null) {
    String noneValue = libs.SIP_Dashboards_Commons.ConstConfig.EMPTY_DIMENSION_VALUE
    String yearPeriodCombination = "${yearEntry}-${periodEntry}"
    String periodValue = periodEntry != null && periodEntry != noneValue ? yearPeriodCombination : yearEntry

    return api.getDatamartContext().calendar().getTimePeriod(periodValue)
}

protected CalendarUtil.TimePeriod getComparisonTimePeriod(String yearInput, String comparisonPeriodInput, CalendarUtil.TimePeriod periodOutput) {
    if (yearInput) {
        return getTimePeriod(yearInput, comparisonPeriodInput)
    } else if (comparisonPeriodInput == null) {
        return periodOutput.add(-1)
    } else {
        String prevYear = periodOutput.getStartDate()
                .getAt(java.util.Calendar.YEAR)

        return getTimePeriod(prevYear, comparisonPeriodInput)
    }
}

/**
 * Calculates the Other Effects that are used in the Causality Dashboards.
 * The other effects are calculated by: comparisonPeriod - basePeriod - all other effects.
 * @param basePeriod base period total value of a measure. Can be for example total revenue of T1.
 * @param comparisonPeriod comparison period total value of a measure. Can be for example total revenue of T2.
 * @param figures List defining the list of all the other effects that will be considered in the calculation
 * @return an Other effects value
 */
protected BigDecimal calculateOtherEffects(BigDecimal basePeriod, BigDecimal comparisonPeriod, List<BigDecimal> figures) {
    BigDecimal nonNullFigures = figures?.findAll { it }?.sum() ?: BigDecimal.ZERO

    return comparisonPeriod - basePeriod - nonNullFigures
}

/**
 * Retrieves the Highchart defined structure for a given single data point.
 * Used for all the middle-points in the Causality Dashboards.
 * Applies proper formatting for the value.
 * The structure returned is of form:
 * ["name": columnLabel, "y": yValue]
 * @param showAsPercentage states whether the chart is displayed in percentages. Usually fetched from ShowAsPercentage user entry
 * @param yValue formatted value of the data point
 * @param percentageBase percentage base used for the percentage calculations
 * @param columnLabel label for the data point
 * @return a Highchart compliant structure of the data point
 */
protected Map prepareChartDataField(Boolean showAsPercentage, BigDecimal yValue, BigDecimal percentageBase, String columnLabel) {
    if (showAsPercentage) {
        yValue = libs.SIP_Dashboards_Commons.MathUtils.getPercentageRatio(yValue, percentageBase)
    }

    return prepareAdjustmentStructure(columnLabel, yValue)
}

/**
 * Retrieves the Highchart defined structure for the provided data point that's defined as a sum.
 * Used for last data points in the Causality Dashboards.
 * Applies proper formatting for the value.
 * The structure returned is of form:
 * ["name": columnLabel, "y": yValue]
 * @param showAsPercentage states whether the chart is displayed in percentages. Usually fetched from ShowAsPercentage user entry
 * @param yValue formatted value of the data point
 * @param percentageBase percentage base used for the percentage calculations
 * @param columnLabel label for the data point
 * @return a Highchart compliant structure of the data point
 */
protected Map prepareChartDataSumField(Boolean showAsPercentage, BigDecimal yValue, BigDecimal percentageBase, String columnLabel) {
    if (showAsPercentage) {
        yValue = libs.SIP_Dashboards_Commons.MathUtils.getPercentageRatio(yValue, percentageBase)
    }

    return prepareSumPricePointStructure(columnLabel, yValue)
}

/**
 * Retrieves the Highchart compliant structure for the provided data point values
 * @param columnLabel label for the data point
 * @param yValue formatted value of the data point
 * @return a Highchart compliant structure of the data point
 */
protected Map prepareAdjustmentStructure(String columnLabel, BigDecimal yValue) {
    return ["name": columnLabel, "y": yValue]
}

/**
 * Retrieves the Highchart compliant structure for the provided data point that's defined as a sum.
 * The sum values in Causality dashboards are usually the last data points
 * @param name label for the data point
 * @param yValue formatted value of the data point
 * @return a Highchart compliant structure of the sum data point
 */
protected Map prepareSumPricePointStructure(String name, BigDecimal yValue) {
    return [name: name, isSum: true, y: yValue]
}

/**
 * Retrieves the Highcharts plot options for the waterfall charts used in Causality Dashboards.
 * The structure of the plot option is defined by Highcharts and cannot be modified.
 * @param positiveColor defines the color for the positive waterfall values
 * @param baseColor defines the color for the regular waterfall values
 * @param formatLabel defines the data labels format that are displayed near the waterfall columns
 * @return a Map defining the waterfall plot options
 */
protected Map getWaterfallPlotOptions(String positiveColor, String baseColor, String formatLabel) {
    return [waterfall: [upColor    : positiveColor,
                        color      : baseColor,
                        borderWidth: 0,
                        dataLabels : [borderWidth: 0,
                                      enabled    : true,
                                      inside     : false,
                                      format     : formatLabel]]]
}

/**
 * Retrieves the tooltip format that will be used in the Causality Dashboards.
 * The format is defined by Highcharts
 * @param shouldShowAsPercentage states whether the chart is displayed in percentages. Usually fetched from ShowAsPercentage user entry
 * @param currencySymbol symbol for the used currency. Value taken from TargetCurrencyData element.
 * @return Highchart compliant tooltip format for the waterfall chart
 */
protected String getTooltipFormat(Boolean shouldShowAsPercentage, String currencySymbol) {
    return "<b>${getValueFormat(shouldShowAsPercentage, currencySymbol)}<b>"
}

/**
 * Retrieves the value format from one of the defined formats in libs.HighchartsLibrary.ConstConfig.TOOLTIP_POINT_Y_FORMAT_TYPES
 * based on whether an absolute or percentage calculations are used.
 * @param shouldShowAsPercentage states whether the chart is displayed in percentages. Usually fetched from ShowAsPercentage user entry
 * @param currencySymbol symbol for the used currency. Value taken from TargetCurrencyData element.
 * @return Highchart compliant format for the waterfall chart
 */
protected String getValueFormat(Boolean shouldShowAsPercentage, String currencySymbol) {
    Map formats = libs.HighchartsLibrary.ConstConfig.TOOLTIP_POINT_Y_FORMAT_TYPES
    String priceWithCurrencySymbol = libs.SIP_Dashboards_Commons.CurrencyUtils.getFormatWithCurrencySymbol(formats.ABSOLUTE_PRICE,
            currencySymbol)

    return shouldShowAsPercentage ? formats.PERCENTAGE : priceWithCurrencySymbol
}

/**
 * Restructure the chart data for the data tab fields
 * @param seriesData original chart data
 * @param isPercentageView defines the percentage display view or not
 * @return the new structure of data tab fields data
 */
protected List restructureDataForDataTabs(List seriesData, boolean isPercentageView) {
    return seriesData?.collect { Map data ->
        return [(libs.SIP_Dashboards_Commons.ConstConfig.DASHBOARD_DATA_TAB_CATEGORY_COLUMN_LABEL): data.name,
                (libs.SIP_Dashboards_Commons.ConstConfig.DASHBOARD_DATA_TAB_SERIES_1_COLUMN_LABEL): libs.SIP_Dashboards_Commons.ChartUtils.getPercentageOrDecimalValueForDataTab(data.y, isPercentageView)]
    }
}

/**
 * Check the ratios are monetary or not
 * @param ratioNumerator String the Ratio numerator
 * @param ratioDenominator String the Ratio denominator
 * @param dmName String the datamart name
 * @return the result that inputted ratios are monetary or not
 */
boolean areRatiosMonetary(String ratioNumerator, String ratioDenominator, String dmName) {
    return isMonetary(ratioNumerator, dmName) && isMonetary(ratioDenominator, dmName)
}

/**
 * Check the field type is MONEY or not
 * @param field String the field
 * @param dmName String the datamart name
 * @return is the field's type monetary
 */
protected boolean isMonetary(String field, String dmName) {
    Map dmFieldTypeMap = getDMFieldTypes(dmName)

    return libs.SIP_Dashboards_Commons.ConstConfig.DM_MONEY_FIELD_TYPE.equalsIgnoreCase(dmFieldTypeMap?.get(field))
}

/**
 * Get the datamart field types
 * @param String dmName the datamart name
 * @return the map of datamart's field types
 */
protected Map getDMFieldTypes(String dmName) {
    return libs.SharedLib.CacheUtils.getOrSet("datamartFieldTypes-$dmName", {
        return api.find("DM", 0, 1, "uniqueName", Filter.equal("uniqueName", dmName))?.getAt(0)?.fields?.collectEntries { field -> return [(field.name), field.type]
        }
    })
}

/**
 * Check if the ratio denominator is quantity field
 * @param sqlConfiguration sql configuration containing data mart fields mapping definition. Stored in SIP_AdvancedConfiguration.
 * @param ratioDenominator String the ratio denominator
 * @return boolean is the Denominator quantity field or not
 */
protected boolean isDenominatorQuantityField(Map sqlConfiguration, String ratioDenominator) {
    return sqlConfiguration.quantity == ratioDenominator
}

/**
 * Get UOM code by given datamark
 * @param dmName String the datamart name
 * @return String return the UOM code
 */
protected String getDatamartUOM(String dmName) {
    return api.find("DM", Filter.equal("uniqueName", dmName))?.getAt(0)?.baseUomCode
}
