import groovy.transform.Field

/**
 * Holds all information about the available map codes for hierarchy level: world
 * Only those hierarchies mentioned in this Map can be drilled down.
 * Information stored:
 * - LABEL - default label used in case user has not defined a custom one
 * - ISO_CODE - by default null, because world does not contain an ISO_CODE, it's there for unification purposes
 * - MAP_CODE - HighMaps code that defines the map to be used for a given entry
 */
@Field Map WORLD_MAP_CODES = [WORLD_CONTINENTS: [LABEL   : "World continents",
                                                 ISO_CODE: null,
                                                 MAP_CODE: "custom/world-continents"]]

/**
 * Holds all information about the available map codes for hierarchy level: continent
 * Only those hierarchies mentioned in this Map can be drilled down.
 * Information stored:
 * - LABEL - default label used in case user has not defined a custom one
 * - ISO_CODE - iso code for the defined entry
 * - MAP_CODE - HighMaps code that defines the map to be used for a given entry
 */
@Field Map CONTINENT_MAP_CODES = [EU: [LABEL   : "Europe",
                                       ISO_CODE: "EU",
                                       MAP_CODE: "custom/europe"],
                                  NA: [LABEL   : "North America",
                                       ISO_CODE: "NA",
                                       MAP_CODE: "custom/north-america"],
                                  AS: [LABEL   : "Asia",
                                       ISO_CODE: "AS",
                                       MAP_CODE: "custom/asia"],
                                  OC: [LABEL   : "Oceania",
                                       ISO_CODE: "OC",
                                       MAP_CODE: "custom/oceania"],
                                  AF: [LABEL   : "Africa",
                                       ISO_CODE: "AF",
                                       MAP_CODE: "custom/africa"],
                                  SA: [LABEL   : "South America",
                                       ISO_CODE: "SA",
                                       MAP_CODE: "custom/south-america"]]

/**
 * Holds all information about the available map codes for hierarchy level: world
 * Only those hierarchies mentioned in this Map can be drilled down.
 * Information stored:
 * - PARENT - defines the higher level hierarchy that contains this entry. Used to create parent-child relations.
 * - LABEL - default label used in case user has not defined a custom one
 * - ISO_CODE - iso code for the defined entry
 * - MAP_CODE - HighMaps code that defines the map to be used for a given entry
 */
@Field Map COUNTRY_MAP_CODES = [AF: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Afghanistan",
                                     ISO_CODE: "AF",
                                     MAP_CODE: "countries/af/af-all"],
                                AL: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Albania",
                                     ISO_CODE: "AL",
                                     MAP_CODE: "countries/al/al-all"],
                                DZ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Algeria",
                                     ISO_CODE: "DZ",
                                     MAP_CODE: "countries/dz/dz-all"],
                                AS: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "American Samoa",
                                     ISO_CODE: "AS",
                                     MAP_CODE: "countries/as/as-all"],
                                AD: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Andorra",
                                     ISO_CODE: "AD",
                                     MAP_CODE: "countries/ad/ad-all"],
                                AO: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Angola",
                                     ISO_CODE: "AO",
                                     MAP_CODE: "countries/ao/ao-all"],
                                AG: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Antigua and Barbuda",
                                     ISO_CODE: "AG",
                                     MAP_CODE: "countries/ag/ag-all"],
                                AR: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Argentina",
                                     ISO_CODE: "AR",
                                     MAP_CODE: "countries/ar/ar-all"],
                                AM: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Armenia",
                                     ISO_CODE: "AM",
                                     MAP_CODE: "countries/am/am-all"],
                                AU: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Australia",
                                     ISO_CODE: "AU",
                                     MAP_CODE: "countries/au/au-all"],
                                AT: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Austria",
                                     ISO_CODE: "AT",
                                     MAP_CODE: "countries/at/at-all"],
                                AZ: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Azerbaijan",
                                     ISO_CODE: "AZ",
                                     MAP_CODE: "countries/az/az-all"],
                                BH: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Bahrain",
                                     ISO_CODE: "BH",
                                     MAP_CODE: "countries/bh/bh-all"],
                                BD: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Bangladesh",
                                     ISO_CODE: "BD",
                                     MAP_CODE: "countries/bd/bd-all"],
                                BB: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Barbados",
                                     ISO_CODE: "BB",
                                     MAP_CODE: "countries/bb/bb-all"],
                                BY: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Belarus",
                                     ISO_CODE: "BY",
                                     MAP_CODE: "countries/by/by-all"],
                                BE: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Belgium",
                                     ISO_CODE: "BE",
                                     MAP_CODE: "countries/be/be-all"],
                                BZ: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Belize",
                                     ISO_CODE: "BZ",
                                     MAP_CODE: "countries/bz/bz-all"],
                                BJ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Benin",
                                     ISO_CODE: "BJ",
                                     MAP_CODE: "countries/bj/bj-all"],
                                BT: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Bhutan",
                                     ISO_CODE: "BT",
                                     MAP_CODE: "countries/bt/bt-all"],
                                BO: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Bolivia",
                                     ISO_CODE: "BO",
                                     MAP_CODE: "countries/bo/bo-all"],
                                BA: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Bosnia and Herzegovina",
                                     ISO_CODE: "BA",
                                     MAP_CODE: "countries/ba/ba-all"],
                                BW: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Botswana",
                                     ISO_CODE: "BW",
                                     MAP_CODE: "countries/bw/bw-all"],
                                BR: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Brazil",
                                     ISO_CODE: "BR",
                                     MAP_CODE: "countries/br/br-all"],
                                BN: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Brunei",
                                     ISO_CODE: "BN",
                                     MAP_CODE: "countries/bn/bn-all"],
                                BG: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Bulgaria",
                                     ISO_CODE: "BG",
                                     MAP_CODE: "countries/bg/bg-all"],
                                BF: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Burkina Faso",
                                     ISO_CODE: "BF",
                                     MAP_CODE: "countries/bf/bf-all"],
                                BI: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Burundi",
                                     ISO_CODE: "BI",
                                     MAP_CODE: "countries/bi/bi-all"],
                                KH: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Cambodia",
                                     ISO_CODE: "KH",
                                     MAP_CODE: "countries/kh/kh-all"],
                                CM: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Cameroon",
                                     ISO_CODE: "CM",
                                     MAP_CODE: "countries/cm/cm-all"],
                                CA: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Canada",
                                     ISO_CODE: "CA",
                                     MAP_CODE: "countries/ca/ca-all"],
                                CV: [PARENT  : "FILL",
                                     LABEL   : "Cape Verde",
                                     ISO_CODE: "CV",
                                     MAP_CODE: "countries/cv/cv-all"],
                                CF: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Central African Republic",
                                     ISO_CODE: "CF",
                                     MAP_CODE: "countries/cf/cf-all"],
                                TD: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Chad",
                                     ISO_CODE: "TD",
                                     MAP_CODE: "countries/td/td-all"],
                                CL: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Chile",
                                     ISO_CODE: "CL",
                                     MAP_CODE: "countries/cl/cl-all"],
                                CN: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "China",
                                     ISO_CODE: "CN",
                                     MAP_CODE: "countries/cn/cn-all"],
                                CO: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Colombia",
                                     ISO_CODE: "CO",
                                     MAP_CODE: "countries/co/co-all"],
                                KM: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Comoros",
                                     ISO_CODE: "KM",
                                     MAP_CODE: "countries/km/km-all"],
                                CK: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Cook Islands",
                                     ISO_CODE: "CK",
                                     MAP_CODE: "countries/ck/ck-all"],
                                CR: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Costa Rica",
                                     ISO_CODE: "CR",
                                     MAP_CODE: "countries/cr/cr-all"],
                                HR: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Croatia",
                                     ISO_CODE: "HR",
                                     MAP_CODE: "countries/hr/hr-all"],
                                CU: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Cuba",
                                     ISO_CODE: "CU",
                                     MAP_CODE: "countries/cu/cu-all"],
                                CY: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Cyprus",
                                     ISO_CODE: "CY",
                                     MAP_CODE: "countries/cy/cy-all"],
                                CZ: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Czech Republic",
                                     ISO_CODE: "CZ",
                                     MAP_CODE: "countries/cz/cz-all"],
                                CD: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Democratic Republic of the Congo",
                                     ISO_CODE: "CD",
                                     MAP_CODE: "countries/cd/cd-all"],
                                DK: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Denmark",
                                     ISO_CODE: "DK",
                                     MAP_CODE: "countries/dk/dk-all"],
                                DJ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Djibouti",
                                     ISO_CODE: "DJ",
                                     MAP_CODE: "countries/dj/dj-all"],
                                DM: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Dominica",
                                     ISO_CODE: "DM",
                                     MAP_CODE: "countries/dm/dm-all"],
                                DO: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Dominican Republic",
                                     ISO_CODE: "DO",
                                     MAP_CODE: "countries/do/do-all"],
                                TL: [PARENT  : "FILL",
                                     LABEL   : "East Timor",
                                     ISO_CODE: "TL",
                                     MAP_CODE: "countries/tl/tl-all"],
                                EC: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Ecuador",
                                     ISO_CODE: "EC",
                                     MAP_CODE: "countries/ec/ec-all"],
                                EG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Egypt",
                                     ISO_CODE: "EG",
                                     MAP_CODE: "countries/eg/eg-all"],
                                SV: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "El Salvador",
                                     ISO_CODE: "SV",
                                     MAP_CODE: "countries/sv/sv-all"],
                                GQ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Equatorial Guinea",
                                     ISO_CODE: "GQ",
                                     MAP_CODE: "countries/gq/gq-all"],
                                ER: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Eritrea",
                                     ISO_CODE: "ER",
                                     MAP_CODE: "countries/er/er-all"],
                                EE: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Estonia",
                                     ISO_CODE: "EE",
                                     MAP_CODE: "countries/ee/ee-all"],
                                ET: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Ethiopia",
                                     ISO_CODE: "ET",
                                     MAP_CODE: "countries/et/et-all"],
                                FO: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Faroe Islands",
                                     ISO_CODE: "FO",
                                     MAP_CODE: "countries/fo/fo-all"],
                                FJ: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Fiji",
                                     ISO_CODE: "FJ",
                                     MAP_CODE: "countries/fj/fj-all"],
                                FI: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Finland",
                                     ISO_CODE: "FI",
                                     MAP_CODE: "countries/fi/fi-all"],
                                FR: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "France",
                                     ISO_CODE: "FR",
                                     MAP_CODE: "countries/fr/fr-all"],
                                GA: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Gabon",
                                     ISO_CODE: "GA",
                                     MAP_CODE: "countries/ga/ga-all"],
                                GM: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Gambia",
                                     ISO_CODE: "GM",
                                     MAP_CODE: "countries/gm/gm-all"],
                                GE: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Georgia",
                                     ISO_CODE: "GE",
                                     MAP_CODE: "countries/ge/ge-all"],
                                DE: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Germany",
                                     ISO_CODE: "DE",
                                     MAP_CODE: "countries/de/de-all"],
                                GH: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Ghana",
                                     ISO_CODE: "GH",
                                     MAP_CODE: "countries/gh/gh-all"],
                                GR: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Greece",
                                     ISO_CODE: "GR",
                                     MAP_CODE: "countries/gr/gr-all"],
                                GL: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Greenland",
                                     ISO_CODE: "GL",
                                     MAP_CODE: "countries/gl/gl-all"],
                                GD: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Grenada",
                                     ISO_CODE: "GD",
                                     MAP_CODE: "countries/gd/gd-all"],
                                GU: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Guam",
                                     ISO_CODE: "GU",
                                     MAP_CODE: "countries/gu/gu-all"],
                                GT: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Guatemala",
                                     ISO_CODE: "GT",
                                     MAP_CODE: "countries/gt/gt-all"],
                                GN: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Guinea",
                                     ISO_CODE: "GN",
                                     MAP_CODE: "countries/gn/gn-all"],
                                GW: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Guinea Bissau",
                                     ISO_CODE: "GW",
                                     MAP_CODE: "countries/gw/gw-all"],
                                GY: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Guyana",
                                     ISO_CODE: "GY",
                                     MAP_CODE: "countries/gy/gy-all"],
                                HT: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Haiti",
                                     ISO_CODE: "HT",
                                     MAP_CODE: "countries/ht/ht-all"],
                                HN: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Honduras",
                                     ISO_CODE: "HN",
                                     MAP_CODE: "countries/hn/hn-all"],
                                HU: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Hungary",
                                     ISO_CODE: "HU",
                                     MAP_CODE: "countries/hu/hu-all"],
                                IS: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Iceland",
                                     ISO_CODE: "IS",
                                     MAP_CODE: "countries/is/is-all"],
                                IN: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "India",
                                     ISO_CODE: "IN",
                                     MAP_CODE: "countries/in/in-all"],
                                ID: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Indonesia",
                                     ISO_CODE: "ID",
                                     MAP_CODE: "countries/id/id-all"],
                                IR: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Iran",
                                     ISO_CODE: "IR",
                                     MAP_CODE: "countries/ir/ir-all"],
                                IQ: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Iraq",
                                     ISO_CODE: "IQ",
                                     MAP_CODE: "countries/iq/iq-all"],
                                IE: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Ireland",
                                     ISO_CODE: "IE",
                                     MAP_CODE: "countries/ie/ie-all"],
                                IL: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Israel",
                                     ISO_CODE: "IL",
                                     MAP_CODE: "countries/il/il-all"],
                                IT: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Italy",
                                     ISO_CODE: "IT",
                                     MAP_CODE: "countries/it/it-all"],
                                CI: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Ivory Coast",
                                     ISO_CODE: "CI",
                                     MAP_CODE: "countries/ci/ci-all"],
                                JM: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Jamaica",
                                     ISO_CODE: "JM",
                                     MAP_CODE: "countries/jm/jm-all"],
                                JP: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Japan",
                                     ISO_CODE: "JP",
                                     MAP_CODE: "countries/jp/jp-all"],
                                JO: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Jordan",
                                     ISO_CODE: "JO",
                                     MAP_CODE: "countries/jo/jo-all"],
                                KZ: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Kazakhstan",
                                     ISO_CODE: "KZ",
                                     MAP_CODE: "countries/kz/kz-all"],
                                KE: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Kenya",
                                     ISO_CODE: "KE",
                                     MAP_CODE: "countries/ke/ke-all"],
                                KV: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Kosovo",
                                     ISO_CODE: "KV",
                                     MAP_CODE: "countries/kv/kv-all"],
                                KW: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Kuwait",
                                     ISO_CODE: "KW",
                                     MAP_CODE: "countries/kw/kw-all"],
                                KG: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Kyrgyzstan",
                                     ISO_CODE: "KG",
                                     MAP_CODE: "countries/kg/kg-all"],
                                LA: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Laos",
                                     ISO_CODE: "LA",
                                     MAP_CODE: "countries/la/la-all"],
                                LV: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Latvia",
                                     ISO_CODE: "LV",
                                     MAP_CODE: "countries/lv/lv-all"],
                                LB: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Lebanon",
                                     ISO_CODE: "LB",
                                     MAP_CODE: "countries/lb/lb-all"],
                                LS: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Lesotho",
                                     ISO_CODE: "LS",
                                     MAP_CODE: "countries/ls/ls-all"],
                                LR: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Liberia",
                                     ISO_CODE: "LR",
                                     MAP_CODE: "countries/lr/lr-all"],
                                LY: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Libya",
                                     ISO_CODE: "LY",
                                     MAP_CODE: "countries/ly/ly-all"],
                                LI: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Liechtenstein",
                                     ISO_CODE: "LI",
                                     MAP_CODE: "countries/li/li-all"],
                                LT: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Lithuania",
                                     ISO_CODE: "LT",
                                     MAP_CODE: "countries/lt/lt-all"],
                                LU: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Luxembourg",
                                     ISO_CODE: "LU",
                                     MAP_CODE: "countries/lu/lu-all"],
                                MK: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Macedonia",
                                     ISO_CODE: "MK",
                                     MAP_CODE: "countries/mk/mk-all"],
                                MG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Madagascar",
                                     ISO_CODE: "MG",
                                     MAP_CODE: "countries/mg/mg-all"],
                                MW: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Malawi",
                                     ISO_CODE: "MW",
                                     MAP_CODE: "countries/mw/mw-all"],
                                MY: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Malaysia",
                                     ISO_CODE: "MY",
                                     MAP_CODE: "countries/my/my-all"],
                                ML: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Mali",
                                     ISO_CODE: "ML",
                                     MAP_CODE: "countries/ml/ml-all"],
                                MT: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Malta",
                                     ISO_CODE: "MT",
                                     MAP_CODE: "countries/mt/mt-all"],
                                MR: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Mauritania",
                                     ISO_CODE: "MR",
                                     MAP_CODE: "countries/mr/mr-all"],
                                MU: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Mauritius",
                                     ISO_CODE: "MU",
                                     MAP_CODE: "countries/mu/mu-all"],
                                MX: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Mexico",
                                     ISO_CODE: "MX",
                                     MAP_CODE: "countries/mx/mx-all"],
                                MD: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Moldova",
                                     ISO_CODE: "MD",
                                     MAP_CODE: "countries/md/md-all"],
                                MC: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Monaco",
                                     ISO_CODE: "MC",
                                     MAP_CODE: "countries/mc/mc-all"],
                                MN: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Mongolia",
                                     ISO_CODE: "MN",
                                     MAP_CODE: "countries/mn/mn-all"],
                                ME: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Montenegro",
                                     ISO_CODE: "ME",
                                     MAP_CODE: "countries/me/me-all"],
                                MA: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Morocco",
                                     ISO_CODE: "MA",
                                     MAP_CODE: "countries/ma/ma-all"],
                                MZ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Mozambique",
                                     ISO_CODE: "MZ",
                                     MAP_CODE: "countries/mz/mz-all"],
                                MM: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Myanmar",
                                     ISO_CODE: "MM",
                                     MAP_CODE: "countries/mm/mm-all"],
                                NA: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Namibia",
                                     ISO_CODE: "NA",
                                     MAP_CODE: "countries/na/na-all"],
                                NR: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Nauru",
                                     ISO_CODE: "NR",
                                     MAP_CODE: "countries/nr/nr-all"],
                                NP: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Nepal",
                                     ISO_CODE: "NP",
                                     MAP_CODE: "countries/np/np-all"],
                                NC: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "New Caledonia",
                                     ISO_CODE: "NC",
                                     MAP_CODE: "countries/nc/nc-all"],
                                NZ: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "New Zealand",
                                     ISO_CODE: "NZ",
                                     MAP_CODE: "countries/nz/nz-all"],
                                NI: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Nicaragua",
                                     ISO_CODE: "NI",
                                     MAP_CODE: "countries/ni/ni-all"],
                                NE: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Niger",
                                     ISO_CODE: "NG",
                                     MAP_CODE: "countries/ne/ne-all"],
                                NG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Nigeria",
                                     ISO_CODE: "NG",
                                     MAP_CODE: "countries/ng/ng-all"],
                                KP: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "North Korea",
                                     ISO_CODE: "KP",
                                     MAP_CODE: "countries/kp/kp-all"],
                                MP: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Northern Mariana Islands",
                                     ISO_CODE: "MP",
                                     MAP_CODE: "countries/mp/mp-all"],
                                NO: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Norway",
                                     ISO_CODE: "NO",
                                     MAP_CODE: "countries/no/no-all"],
                                OM: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Oman",
                                     ISO_CODE: "OM",
                                     MAP_CODE: "countries/om/om-all"],
                                PK: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Pakistan",
                                     ISO_CODE: "PK",
                                     MAP_CODE: "countries/pk/pk-all"],
                                PW: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Palau",
                                     ISO_CODE: "PW",
                                     MAP_CODE: "countries/pw/pw-all"],
                                PA: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Panama",
                                     ISO_CODE: "PA",
                                     MAP_CODE: "countries/pa/pa-all"],
                                PG: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Papua New Guinea",
                                     ISO_CODE: "PG",
                                     MAP_CODE: "countries/pg/pg-all"],
                                PY: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Paraguay",
                                     ISO_CODE: "PY",
                                     MAP_CODE: "countries/py/py-all"],
                                PE: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Peru",
                                     ISO_CODE: "PE",
                                     MAP_CODE: "countries/pe/pe-all"],
                                PH: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Philippines",
                                     ISO_CODE: "PH",
                                     MAP_CODE: "countries/ph/ph-all"],
                                PL: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Poland",
                                     ISO_CODE: "PL",
                                     MAP_CODE: "countries/pl/pl-all"],
                                PT: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Portugal",
                                     ISO_CODE: "PT",
                                     MAP_CODE: "countries/pt/pt-all"],
                                PR: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Puerto Rico",
                                     ISO_CODE: "PR",
                                     MAP_CODE: "countries/pr/pr-all"],
                                QA: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Qatar",
                                     ISO_CODE: "QA",
                                     MAP_CODE: "countries/qa/qa-all"],
                                RS: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Republic of Serbia",
                                     ISO_CODE: "RS",
                                     MAP_CODE: "countries/rs/rs-all"],
                                CG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Republic of the Congo",
                                     ISO_CODE: "CG",
                                     MAP_CODE: "countries/cg/cg-all"],
                                RO: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Romania",
                                     ISO_CODE: "RO",
                                     MAP_CODE: "countries/ro/ro-all"],
                                RU: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Russia",
                                     ISO_CODE: "RU",
                                     MAP_CODE: "countries/ru/ru-all"],
                                RW: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Rwanda",
                                     ISO_CODE: "RW",
                                     MAP_CODE: "countries/rw/rw-all"],
                                KN: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Saint Kitts and Nevis",
                                     ISO_CODE: "KN",
                                     MAP_CODE: "countries/kn/kn-all"],
                                LC: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Saint Lucia",
                                     ISO_CODE: "LC",
                                     MAP_CODE: "countries/lc/lc-all"],
                                VC: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Saint Vincent and the Grenadines",
                                     ISO_CODE: "VC",
                                     MAP_CODE: "countries/vc/vc-all"],
                                WS: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Samoa",
                                     ISO_CODE: "WS",
                                     MAP_CODE: "countries/ws/ws-all"],
                                SM: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "San Marino",
                                     ISO_CODE: "SM",
                                     MAP_CODE: "countries/sm/sm-all"],
                                ST: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Sao Tome and Principe",
                                     ISO_CODE: "ST",
                                     MAP_CODE: "countries/st/st-all"],
                                SA: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Saudi Arabia",
                                     ISO_CODE: "SA",
                                     MAP_CODE: "countries/sa/sa-all"],
                                SN: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Senegal",
                                     ISO_CODE: "SN",
                                     MAP_CODE: "countries/sn/sn-all"],
                                SC: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Seychelles",
                                     ISO_CODE: "SC",
                                     MAP_CODE: "countries/sc/sc-all"],
                                SL: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Sierra Leone",
                                     ISO_CODE: "SL",
                                     MAP_CODE: "countries/sl/sl-all"],
                                SG: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Singapore",
                                     ISO_CODE: "SG",
                                     MAP_CODE: "countries/sg/sg-all"],
                                SK: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Slovakia",
                                     ISO_CODE: "SK",
                                     MAP_CODE: "countries/sk/sk-all"],
                                SI: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Slovenia",
                                     ISO_CODE: "SI",
                                     MAP_CODE: "countries/si/si-all"],
                                SB: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Solomon Islands",
                                     ISO_CODE: "SB",
                                     MAP_CODE: "countries/sb/sb-all"],
                                SO: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Somalia",
                                     ISO_CODE: "SO",
                                     MAP_CODE: "countries/so/so-all"],
                                SX: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Somaliland",
                                     ISO_CODE: "SX",
                                     MAP_CODE: "countries/sx/sx-all"],
                                ZA: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "South Africa",
                                     ISO_CODE: "ZA",
                                     MAP_CODE: "countries/za/za-all"],
                                KR: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "South Korea",
                                     ISO_CODE: "KR",
                                     MAP_CODE: "countries/kr/kr-all"],
                                SS: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "South Sudan",
                                     ISO_CODE: "SS",
                                     MAP_CODE: "countries/ss/ss-all"],
                                ES: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Spain",
                                     ISO_CODE: "ES",
                                     MAP_CODE: "countries/es/es-all"],
                                LK: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Sri Lanka",
                                     ISO_CODE: "LK",
                                     MAP_CODE: "countries/lk/lk-all"],
                                SD: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Sudan",
                                     ISO_CODE: "SD",
                                     MAP_CODE: "countries/sd/sd-all"],
                                SR: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Suriname",
                                     ISO_CODE: "SR",
                                     MAP_CODE: "countries/sr/sr-all"],
                                SZ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Swaziland",
                                     ISO_CODE: "SZ",
                                     MAP_CODE: "countries/sz/sz-all"],
                                SE: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Sweden",
                                     ISO_CODE: "SE",
                                     MAP_CODE: "countries/se/se-all"],
                                CH: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Switzerland",
                                     ISO_CODE: "CH",
                                     MAP_CODE: "countries/ch/ch-all"],
                                SY: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Syria",
                                     ISO_CODE: "SY",
                                     MAP_CODE: "countries/sy/sy-all"],
                                TW: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Taiwan",
                                     ISO_CODE: "TW",
                                     MAP_CODE: "countries/tw/tw-all"],
                                TJ: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Tajikistan",
                                     ISO_CODE: "TJ",
                                     MAP_CODE: "countries/tj/tj-all"],
                                TH: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Thailand",
                                     ISO_CODE: "TH",
                                     MAP_CODE: "countries/th/th-all"],
                                BS: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "The Bahamas",
                                     ISO_CODE: "BS",
                                     MAP_CODE: "countries/bs/bs-all"],
                                NL: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "The Netherlands",
                                     ISO_CODE: "NL",
                                     MAP_CODE: "countries/nl/nl-all"],
                                TG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Togo",
                                     ISO_CODE: "TG",
                                     MAP_CODE: "countries/tg/tg-all"],
                                TT: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "Trinidad and Tobago",
                                     ISO_CODE: "TT",
                                     MAP_CODE: "countries/tt/tt-all"],
                                TN: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Tunisia",
                                     ISO_CODE: "TN",
                                     MAP_CODE: "countries/tn/tn-all"],
                                TR: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Turkey",
                                     ISO_CODE: "TR",
                                     MAP_CODE: "countries/tr/tr-all"],
                                TM: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Turkmenistan",
                                     ISO_CODE: "TM",
                                     MAP_CODE: "countries/tm/tm-all"],
                                UG: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Uganda",
                                     ISO_CODE: "UG",
                                     MAP_CODE: "countries/ug/ug-all"],
                                UA: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "Ukraine",
                                     ISO_CODE: "UA",
                                     MAP_CODE: "countries/ua/ua-all"],
                                AE: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "United Arab Emirates",
                                     ISO_CODE: "AE",
                                     MAP_CODE: "countries/ae/ae-all"],
                                GB: [PARENT  : CONTINENT_MAP_CODES.EU,
                                     LABEL   : "United Kingdom",
                                     ISO_CODE: "GB",
                                     MAP_CODE: "countries/gb/gb-all"],
                                TZ: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "United Republic of Tanzania",
                                     ISO_CODE: "TZ",
                                     MAP_CODE: "countries/tz/tz-all"],
                                VI: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "United States Virgin Islands",
                                     ISO_CODE: "VI",
                                     MAP_CODE: "countries/vi/vi-all"],
                                US: [PARENT  : CONTINENT_MAP_CODES.NA,
                                     LABEL   : "United States of America",
                                     ISO_CODE: "US",
                                     MAP_CODE: "countries/us/us-all"],
                                UY: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Uruguay",
                                     ISO_CODE: "UY",
                                     MAP_CODE: "countries/uy/uy-all"],
                                UZ: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Uzbekistan",
                                     ISO_CODE: "UZ",
                                     MAP_CODE: "countries/uz/uz-all"],
                                VU: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Vanuatu",
                                     ISO_CODE: "VU",
                                     MAP_CODE: "countries/vu/vu-all"],
                                VE: [PARENT  : CONTINENT_MAP_CODES.SA,
                                     LABEL   : "Venezuela",
                                     ISO_CODE: "VE",
                                     MAP_CODE: "countries/ve/ve-all"],
                                VN: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Vietnam",
                                     ISO_CODE: "VN",
                                     MAP_CODE: "countries/vn/vn-all"],
                                WF: [PARENT  : CONTINENT_MAP_CODES.OC,
                                     LABEL   : "Wallis and Futuna",
                                     ISO_CODE: "WF",
                                     MAP_CODE: "countries/wf/wf-all"],
                                EH: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Western Sahara",
                                     ISO_CODE: "EH",
                                     MAP_CODE: "countries/eh/eh-all"],
                                YE: [PARENT  : CONTINENT_MAP_CODES.AS,
                                     LABEL   : "Yemen",
                                     ISO_CODE: "YE",
                                     MAP_CODE: "countries/ye/ye-all"],
                                ZM: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Zambia",
                                     ISO_CODE: "ZM",
                                     MAP_CODE: "countries/zm/zm-all"],
                                ZW: [PARENT  : CONTINENT_MAP_CODES.AF,
                                     LABEL   : "Zimbabwe",
                                     ISO_CODE: "ZW",
                                     MAP_CODE: "countries/zw/zw-all"]]

/**
 * Holds all information about the available map codes for hierarchy level: region
 * Only those hierarchies mentioned in this Map can be drilled down.
 * Information stored:
 * - PARENT - defines the higher level hierarchy that contains this entry. Used to create parent-child relations.
 * - LABEL - default label used in case user has not defined a custom one
 * - ISO_CODE - iso code for the defined entry
 * - MAP_CODE - HighMaps code that defines the map to be used for a given entry
 */
@Field Map REGION_MAP_CODES = [:]


/**
 * Holds all information about the available map codes for hierarchy level: sector
 * Only those hierarchies mentioned in this Map can be drilled down.
 * Information stored:
 * - PARENT - defines the higher level hierarchy that contains this entry. Used to create parent-child relations.
 * - LABEL - default label used in case user has not defined a custom one
 * - ISO_CODE - iso code for the defined entry
 * - MAP_CODE - HighMaps code that defines the map to be used for a given entry
 */
@Field Map SECTOR_MAP_CODES = [:]