import net.pricefx.common.util.CalendarUtil

/**
 * Provides a list of date filters based on the dateFrom and dateTo user entries.
 * @param dateFromInputElement date from as generated by the DateFromInput entry user input. Provides starting date for the retrieved data.
 * @param dateToInputElement date to as generated by the DateToInput entry user input. Provides end date for the retrieved data.
 * @param transactionDateColumn name of the pricingDate column. Stored in SQL_CONFIGURATION.
 * @return list of date filters based on the provided date ranges
 */
List generateDateFromToFilters(def dateFromInputElement, def dateToInputElement, String transactionDateColumn) {
    return [dateFromInputElement ? Filter.greaterOrEqual(transactionDateColumn, dateFromInputElement) : null,
            dateToInputElement ? Filter.lessOrEqual(transactionDateColumn, dateToInputElement) : null]
}

/**
 * Retrieves the labels for the listed datamart dimensions.
 * Can append additional Empty dimension if necessary. The label of the empty dimension is defined in libs.SIP_Dashboards_Commons.ConstConfig.EMPTY_DIMENSION
 * @param datamartName name of the datamart that will be the source of the labels
 * @param names names of the datamart fields to be used as dimensions
 * @param includeEmptyDimension flag defining whether the Empty dimension should be used
 * @return a Map containing the mapping of field name and a field label
 */
Map getNameLabelPairs(String dataSource, List names, boolean includeEmptyDimension = false) {
    def dmCtx = api.getDatamartContext()
    def table = dmCtx.getTable(dataSource)

    //TODO: Add warning when such column is missing during Error handling task https://pricefx.atlassian.net/browse/PFPCS-1663
    Map nameLabelPairs = names.findAll { table.getColumn(it)?.label }
            .collectEntries { it ->
                return [(it): table.getColumn(it).label]
            }

    return includeEmptyDimension ?
            nameLabelPairs + libs.SIP_Dashboards_Commons.ConstConfig.EMPTY_DIMENSION :
            nameLabelPairs
}

CalendarUtil.TimePeriod createCustomTimePeriod(String dateFrom, String dateTo) {
    return api.getDatamartContext().calendar().newTimePeriod(dateFrom, dateTo, CalendarUtil.TimeUnit.DAY.getName())
}